version: "3.8"

services:
  lead_gen_dev_service:
    build: .
    container_name: lead_gen_dev_service
    ports:
      - "8081:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
